language: python

python:
    - 2.7
    - 2.6
env:
    - NUMPY_VERSION=1.6.2 ONLY_EGG_INFO=false
    - NUMPY_VERSION=1.5.1 ONLY_EGG_INFO=false
    - NUMPY_VERSION=1.4.1 ONLY_EGG_INFO=false
    
before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq 
   - sudo apt-get install -qq python-numpy python-scipy 
install: 
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
   - pip install matplotlib --use-mirrors
   - if ! $ONLY_EGG_INFO; then pip -q install Cython --use-mirrors; fi
script: if $ONLY_EGG_INFO;then python setup.py egg_info;else python setup.py test;fi
